
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CURRENCY DECLARE ID NUMBER PLUS TIMESexpression : DECLARE ID factorexpression : expression PLUS termexpression : termterm : factorfactor : NUMBERfactor : CURRENCYfactor : ID'
    
_lr_action_items = {'DECLARE':([0,],[2,]),'NUMBER':([0,8,9,],[6,6,6,]),'CURRENCY':([0,8,9,],[7,7,7,]),'ID':([0,2,8,9,],[3,9,3,3,]),'$end':([1,3,4,5,6,7,10,11,],[0,-7,-4,-3,-5,-6,-2,-1,]),'PLUS':([1,3,4,5,6,7,10,11,],[8,-7,-4,-3,-5,-6,-2,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'factor':([0,8,9,],[4,4,11,]),'term':([0,8,],[5,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> DECLARE ID factor','expression',3,'p_expression_declare','parser.py',10),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',20),
  ('expression -> term','expression',1,'p_expression_term','parser.py',38),
  ('term -> factor','term',1,'p_term_factor','parser.py',42),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',46),
  ('factor -> CURRENCY','factor',1,'p_factor_currency','parser.py',50),
  ('factor -> ID','factor',1,'p_factor_id','parser.py',68),
]
